#!/bin/sh

if source ~/.screenlayout/docked.sh
then
	source ~/.dotfiles/host-nuc/xinit.local
	yes | rcup -B nuc
else
	source ~/.dotfiles/host-xps/xinit.local
	yes | rcup -B xps
fi

slock & disown

# setup a gnome keyring
dbus-update-activation-environment --systemd DISPLAY
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

# use scroll lock to switch between english/hebrew
setxkbmap -layout 'us, il' -option 'grp:sclk_toggle,grp_led:scroll'
xmodmap -e 'remove control = Control_R' -e 'add mod4 = Control_R'
#setxkbmap -option caps:swapescape
xset r rate 400 30

autocutsel -fork &
autocutsel -selection PRIMARY -fork &

export PATH="$PATH:$HOME/.scripts"

exec i3
