#!/bin/bash

bak="${1?'missing file operand'}.bak"

#while [ -e "$bak" ]; do
#	local bak="${bak}k"
#done

# recursion !!
[ -e "$bak" ] && bak "$bak"

# this way we preserve original modification time
mv "$1" "$bak"
cp "$bak" "$1"

