#!/bin/bash

[ -n "$1" ] && dir="$1" || dir="."
shift
[ -n "$1" ] && names="-name $1" || names=
shift

for name; do names="$names -o -name $name"; done
find $dir -type f $names | xargs -d'\n' du -s | sort -nr | cut -f2 | xargs -d'\n' du -sh
