#!/bin/bash


if [[ $# -eq 0 ]]; then
	echo psgrep: no matching criteria specified >&2
	return 1
elif [[ $# -gt 1 ]]; then
	echo psgrep: only one pattern can be provided >&2
	return 1
fi

ps auxc |
	awk -v pat="$1" '
	BEGIN {
		pat = tolower(pat)
	}
	NR == 1 {
		header = $0
		next
	}
	tolower($11) ~ pat {
		if (!hits)
			print header
		hits++
		print $0
	}
	END {
		#if (hits)
		#	printf "%d match%s found\n", hits, (hits == 1 ? "" : "es")
		if (!hits)
			exit 1
	}'
