#!/bin/bash

if command -v apt > /dev/null; then
	sudo apt update && sudo apt -y upgrade
elif command -v brew > /dev/null; then
	brew update && brew upgrade
	exit 1
fi

case $OSTYPE in
linux*)
	if [ -f /etc/os-release ]; then
		. /etc/os-release
	fi

	case $ID in
	arch)
		if command -v packer > /dev/null; then
			packer -Syu --noconfirm
		else
			sudo pacman -Syu
		fi
		;;
	ubuntu)
		sudo apt-get update &&
		sudo apt-get -y upgrade
		;;
	*)
		echo This linux is not supported
		exit 1
	esac
	;;
darwin*)
	brew update && brew upgrade
	;;
esac
		

sudo -k
