#!/bin/bash

if command -v apt > /dev/null; then
	sudo apt update && sudo apt -y upgrade
elif command -v brew > /dev/null; then
	brew update && brew upgrade
elif command -v packer > /dev/null; then
	packer -Syu --noconfirm
elif command -v pacman > /dev/null; then
	sudo pacman -Syu
else
	echo "No upgrade program was found"
	exit 1
fi

sudo -k
