#!/bin/sh

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width			2
bspc config window_gap				0
bspc config split_ratio				0.50
bspc config borderless_monocle		true
bspc config gapless_monocle			true
bspc config focus_follows_pointer	true
bspc config presel_feedback_color	"#66ffc2"
bspc config focused_border_color	"#777777"
bspc config normal_border_color		"#333333"
bspc config ignore_ewmh_focus		true

dropdown="dropdown"
bspc rule -a "*:$dropdown" hidden=on
bspc rule -a "*:$dropdown" sticky=on
bspc rule -a "*:$dropdown" state=floating
bspc query -N -n .hidden >/dev/null || spawn termite --name "$dropdown" -e tmux

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a Termite:termite -o node=@^1:^1:/1
bspc rule -a Termite:termite -o node=@^1:^1:/2
bspc rule -a Brave-browser:brave-browser -o node=@^1:^2:/
bspc rule -a Thunar:thunar -o node=@^1:^3:/
bspc rule -a Termite:neomutt -o node=@^1:^9:/
bspc rule -a Spotify:spotify -o node=@^1:^10:/

spawn termite
spawn termite
spawn brave
spawn thunar
spawn termite -e neomutt --name neomutt

cd ~/.config/bspwm
. ./profile
[ -e "$PANEL_FIFO" ] && bspc subscribe report > "$PANEL_FIFO" &
pgrep -x panel > /dev/null || ./panel &

spawn sh -c "sleep 0.25 && $SPOTIFY"
