#!/bin/sh

bspc rule -r "*"

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width			2
bspc config window_gap				0
bspc config split_ratio				0.50
bspc config borderless_monocle		true
bspc config gapless_monocle			true
bspc config focus_follows_pointer	true

. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color		"#333333"
bspc config active_border_color		"$color2"
bspc config focused_border_color	"$color1"
bspc config presel_feedback_color	"$color1"

# bspc config presel_feedback_color	'#66ffc2'
# bspc config focused_border_color	'#777777'
# bspc config normal_border_color		'#333333'

bspc config ignore_ewmh_focus		true
spawn sh -c 'xdo id -m -a brave && sleep 2 && bspc config ignore_ewmh_focus false'

xsetroot -cursor_name left_ptr

# Random rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# launch initial programs
pgrep -x "$TERMINAL" || {
	bspc rule -a St:st -o node=@^1:^1:/1
	bspc rule -a St:st -o node=@^1:^1:/2
	bspc rule -a St:neomutt -o node=@^1:^9:/
	spawn st
	spawn st
	spawn st -n neomutt -e neomutt
}
pgrep -x brave || {
	bspc rule -a Brave-browser:brave-browser -o node=@^1:^2:/
	spawn brave
}
pgrep -x thunar || {
	bspc rule -a Thunar:thunar -o node=@^1:^3:/
	spawn thunar
}
pgrep -x spotify || {
	bspc rule -a Spotify:spotify -o node=@^1:^10:/
	spawn sh -c "sleep 0.25 && spotify"
}

# Scratchpad rules
dropdown="dropdown"
bspc rule -a "*:$dropdown" hidden=on
bspc rule -a "*:$dropdown" sticky=on
bspc rule -a "*:$dropdown" state=floating
bspc query -N -n .hidden >/dev/null || spawn st -n "$dropdown" -e tmux

# launch bar
cd ~/.config/bspwm
pgrep -x panel && pkill panel
spawn ./panel
