#!/bin/sh

slock & disown

# setup a gnome keyring
dbus-update-activation-environment --systemd DISPLAY
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

# use scroll lock to switch between english/hebrew
setxkbmap -layout 'us, il' -option 'grp:sclk_toggle,grp_led:scroll'
#setxkbmap -option caps:swapescape
xset r rate 400 30

autocutsel -fork &
autocutsel -selection PRIMARY -fork &

export PATH="$PATH:$HOME/.scripts"
source ~/.xinit.local

exec i3
