#!/bin/sh

# setup a gnome keyring, mainly for chromium/chrome to be happy
dbus-update-activation-environment --systemd DISPLAY
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

# use scroll lock to switch between english/hebrew
setxkbmap -layout 'us, il' -option 'grp:sclk_toggle,grp_led:scroll'
#setxkbmap -option caps:swapescape
xset r rate 400 30

autocutsel -fork &
autocutsel -selection PRIMARY -fork &

PATH="$PATH:$HOME/.scripts"

exec i3
